// Do not edit. This file is machine generated by the Resource DLL Wizard.

library EmC;

{ITE} {DFMFileType} {UContas.dfm}
{ITE} {DFMFileType} {UDMSERVER.dfm}
{ITE} {DFMFileType} {UExportAccounts.dfm}
{ITE} {DFMFileType} {UFavoritos.dfm}
{ITE} {DFMFileType} {UImportAccounts.dfm}
{ITE} {DFMFileType} {Umain.dfm}
{ITE} {DFMFileType} {Umens.dfm}
{ITE} {DFMFileType} {UShowFilterFriends.dfm}
{ITE} {DFMFileType} {vcl\DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl\DBPWDLG.dfm}
{ITE} {RCFileType} {EmC_DRC.rc}

{$R 'UContas.dfm' FContas:TForm}
{$R 'UDMSERVER.dfm' DM_SERVER:TDataModule}
{$R 'UExportAccounts.dfm' FExportAccounts:TForm}
{$R 'UFavoritos.dfm' FFavoritos:TForm}
{$R 'UImportAccounts.dfm' FImportAccounts:TForm}
{$R 'Umain.dfm' Fmain:TForm}
{$R 'Umens.dfm' Fmens:TForm}
{$R 'UShowFilterFriends.dfm' FShowFilterFriends:TForm}
{$R 'vcl\DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl\DBPWDLG.dfm' PasswordDialog:TForm(Form)}
{$R 'EmC_DRC.res' 'EmC_DRC.rc'}

{$E PTB}

begin
end.